POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHRpMTIzIiwiaWQiOiI1ZThiNThmZDkzZWYzMjNhZDgzNTUzOTAiLCJpYXQiOjE1ODczMjc5OTB9.WuA-4IbpVSM-YhaPTkypoe7LOKPz2YwKDPM9DW0QOvw

{
    "title": "MyBlog",
    "author": "Matti Meikäläinen",
    "url": "https://fullstackopen.com/osa3/tietojen_tallettaminen_mongo_db_tietokantaan",
    "likes": 5,
    "userId": "5e83d2055456eb28dc5fa54b"
}